# This is a basic workflow to help you get started with Actions

name: CI rds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "rds" ]
  pull_request:
    branches: [ "rds" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: s3        # <- usa la rama que contiene requirements.txt
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Create python environment with dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          
      - name: Execute tests
        run: |
          source env/bin/activate
          pytest
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: us-east-1
        
      - name: Prueba AWS credentials listar buckets
        run: aws s3 ls 
      - name: Prueba de zappa deploy
        run: |
          source env/bin/activate
          zappa update dev
